#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from mainwindow.ui on Sun Jan 13 18:27:26 2013
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.centralwidget = QtGui.QWidget(MainWindow)

        verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        verticalLayout_2.setMargin(0)
        horizontalLayout = QtGui.QHBoxLayout()

        self.scanButton = KPushButton(self.centralwidget)
        horizontalLayout.addWidget(self.scanButton)

        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        horizontalLayout.addItem(spacerItem)

        self.reduceColorsButton = KPushButton(self.centralwidget)
        horizontalLayout.addWidget(self.reduceColorsButton)

        self.numColorSpinBox = KIntSpinBox(self.centralwidget)
        self.numColorSpinBox.setMinimum(2)
        self.numColorSpinBox.setMaximum(16)
        self.numColorSpinBox.setProperty("value", 8)
        horizontalLayout.addWidget(self.numColorSpinBox)
        verticalLayout_2.addLayout(horizontalLayout)

        self.colorEditorCells = KColorCells(self.centralwidget,4,4)
        verticalLayout_2.addWidget(self.colorEditorCells)

        self.previewView = QtGui.QGraphicsView(self.centralwidget)
        self.previewView.setMinimumSize(QtCore.QSize(400, 400))
        verticalLayout_2.addWidget(self.previewView)

        verticalLayout = QtGui.QVBoxLayout()
        horizontalLayout_2 = QtGui.QHBoxLayout()
        horizontalLayout_3 = QtGui.QHBoxLayout()

        self.baseFileNameRequester = KUrlRequester(self.centralwidget)
        horizontalLayout_3.addWidget(self.baseFileNameRequester)

        self.FileSeqSpinBox = KIntSpinBox(self.centralwidget)
        horizontalLayout_3.addWidget(self.FileSeqSpinBox)

        horizontalLayout_2.addLayout(horizontalLayout_3)

        verticalLayout.addLayout(horizontalLayout_2)

        horizontalLayout_5 = QtGui.QHBoxLayout()

        self.generatedOutputNameTextLabel = QtGui.QLabel(self.centralwidget)
        horizontalLayout_5.addWidget(self.generatedOutputNameTextLabel)

        self.generatedOutputNameLabel = QtGui.QLabel(self.centralwidget)
        horizontalLayout_5.addWidget(self.generatedOutputNameLabel)
        verticalLayout.addLayout(horizontalLayout_5)

        horizontalLayout_4 = QtGui.QHBoxLayout()
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        horizontalLayout_4.addItem(spacerItem1)
        self.saveButton = KPushButton(self.centralwidget)
        horizontalLayout_4.addWidget(self.saveButton)

        verticalLayout.addLayout(horizontalLayout_4)

        verticalLayout_2.addLayout(verticalLayout)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 20))
        self.menuFile = QtGui.QMenu(self.menubar)
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 20))
        MainWindow.setStatusBar(self.statusbar)

        self.actionQuit = QtGui.QAction(MainWindow)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)

        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(kdecore.i18n(_fromUtf8("MainWindow")))
        self.scanButton.setText(kdecore.i18n(_fromUtf8("Scan")))
        self.reduceColorsButton.setText(kdecore.i18n(_fromUtf8("Reduce Colors")))
        self.generatedOutputNameTextLabel.setText(kdecore.i18n(_fromUtf8("Output:")))
        self.generatedOutputNameLabel.setText(kdecore.i18n(_fromUtf8("generated_output_file_name")))
        self.saveButton.setText(kdecore.i18n(_fromUtf8("Save")))
        self.menuFile.setTitle(kdecore.i18n(_fromUtf8("File")))
        self.actionQuit.setText(kdecore.i18n(_fromUtf8("Quit")))

from PyKDE4.kio import KUrlRequester
from PyKDE4.kdeui import KColorCells, KPushButton, KIntSpinBox
